# Data Wrangling II

Create an “Academic performance” dataset of students and perform the following operations using Python.

    Scan all variables for missing values and inconsistencies. If there are missing values and/or

inconsistencies, use any of the suitable techniques to deal with them. 2. Scan all numeric variables for outliers. If there are outliers, use any of the suitable techniques to deal with them. 3. Apply data transformations on at least one of the variables. The purpose of this transformation should be one of the following reasons: to change the scale for better understanding of the variable, to convert a non-linear relation into a linear one, or to decrease the skewness and convert the distribution into a normal distribution. Reason and document your approach properly

# Part 1

removing all inconsistencies and missing values

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

# Z Score
from scipy import stats
# Robust Scaler
#from sklearn.preprocessing import RobustScaler

df = pd.read_csv("/home/student/31233_DSBDAL/Assignment2/uber.csv")
df

In [8]:
df.isna().sum() #list of empty elements

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [11]:
df = df.ffill()
df= df.bfill()
df# using forward fill and backward fill method

Unnamed: 0                            key  fare_amount  \
0         24238194    2015-05-07 19:52:06.0000003          7.5   
1         27835199    2009-07-17 20:04:56.0000002          7.7   
2         44984355   2009-08-24 21:45:00.00000061         12.9   
3         25894730    2009-06-26 08:22:21.0000001          5.3   
4         17610152  2014-08-28 17:47:00.000000188         16.0   
...            ...                            ...          ...   
199995    42598914   2012-10-28 10:49:00.00000053          3.0   
199996    16382965    2014-03-14 01:09:00.0000008          7.5   
199997    27804658   2009-06-29 00:42:00.00000078         30.9   
199998    20259894    2015-05-20 14:56:25.0000004         14.5   
199999    11951496   2010-05-15 04:08:00.00000076         14.1   

                pickup_datetime  pickup_longitude  pickup_latitude  \
0       2015-05-07 19:52:06 UTC        -73.999817        40.738354   
1       2009-07-17 20:04:56 UTC        -73.994355        40.728225   
2       2009-08-24 21:45:00 UTC        -74.005043        40.740770   
3       2009-06-26 08:22:21 UTC        -73.976124        40.790844   
4       2014-08-28 17:47:00 UTC        -73.925023        40.744085   
...                         ...               ...              ...   
199995  2012-10-28 10:49:00 UTC        -73.987042        40.739367   
199996  2014-03-14 01:09:00 UTC        -73.984722        40.736837   
199997  2009-06-29 00:42:00 UTC        -73.986017        40.756487   
199998  2015-05-20 14:56:25 UTC        -73.997124        40.725452   
199999  2010-05-15 04:08:00 UTC        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
0              -73.999512         40.723217                1  
1              -73.994710         40.750325                1  
2              -73.962565         40.772647                1  
3              -73.965316         40.803349                3  
4              -73.973082         40.761247                5  
...                   ...               ...              ...  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1  

[200000 rows x 9 columns]

In [12]:
df.isna().sum()

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
dtype: int64

In [13]:
# To remove the null values we use this
df.interpolate(inplace=True)
df.isna().sum()

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
dtype: int64

In [14]:
df.dtypes

Unnamed: 0             int64
key                   object
fare_amount          float64
pickup_datetime       object
pickup_longitude     float64
pickup_latitude      float64
dropoff_longitude    float64
dropoff_latitude     float64
passenger_count        int64
dtype: object

In [15]:
#rename a column
df.rename(columns={'Unnamed: 0':'Index'},inplace = True)  #note syntax :
df

Index                            key  fare_amount  \
0       24238194    2015-05-07 19:52:06.0000003          7.5   
1       27835199    2009-07-17 20:04:56.0000002          7.7   
2       44984355   2009-08-24 21:45:00.00000061         12.9   
3       25894730    2009-06-26 08:22:21.0000001          5.3   
4       17610152  2014-08-28 17:47:00.000000188         16.0   
...          ...                            ...          ...   
199995  42598914   2012-10-28 10:49:00.00000053          3.0   
199996  16382965    2014-03-14 01:09:00.0000008          7.5   
199997  27804658   2009-06-29 00:42:00.00000078         30.9   
199998  20259894    2015-05-20 14:56:25.0000004         14.5   
199999  11951496   2010-05-15 04:08:00.00000076         14.1   

                pickup_datetime  pickup_longitude  pickup_latitude  \
0       2015-05-07 19:52:06 UTC        -73.999817        40.738354   
1       2009-07-17 20:04:56 UTC        -73.994355        40.728225   
2       2009-08-24 21:45:00 UTC        -74.005043        40.740770   
3       2009-06-26 08:22:21 UTC        -73.976124        40.790844   
4       2014-08-28 17:47:00 UTC        -73.925023        40.744085   
...                         ...               ...              ...   
199995  2012-10-28 10:49:00 UTC        -73.987042        40.739367   
199996  2014-03-14 01:09:00 UTC        -73.984722        40.736837   
199997  2009-06-29 00:42:00 UTC        -73.986017        40.756487   
199998  2015-05-20 14:56:25 UTC        -73.997124        40.725452   
199999  2010-05-15 04:08:00 UTC        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
0              -73.999512         40.723217                1  
1              -73.994710         40.750325                1  
2              -73.962565         40.772647                1  
3              -73.965316         40.803349                3  
4              -73.973082         40.761247                5  
...                   ...               ...              ...  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1  

[200000 rows x 9 columns]

# Part 2 OUTLINERS


## OUTLINERS CHECK AND TECHNIQUES TO DEAL WITH THEM

1) Outliners are those data points that are distant from all other observations and lie outside all other distribution

2) First way to do is Z-score (x-U/σ) method, there u is the central value, all values that lie after 3rd deviation are considered as outliners

3) IQR - inter quartile range all values after 1.5 times of interquartile range ie above 3rd and below 1

    box plot

    Using scatter points



In [16]:
#z=(dataPoint - mean /std-deviation)
z = np.abs(stats.zscore(df['passenger_count']))
z

0         0.493895
1         0.493895
2         0.493895
3         0.949114
4         2.392122
            ...   
199995    0.493895
199996    0.493895
199997    0.227609
199998    0.493895
199999    0.493895
Name: passenger_count, Length: 200000, dtype: float64

In [18]:
#Outliner detection  
arr = np.where(z>3)  
# arr has only the indices where it has z>3 in a list form
print(arr)  
print("total outliners in it ",len(arr[0]))

#remove outliners by below command
# df_no_outliers = df[(z <= 3)] for a new column
# df=df[z<=3]  changes in same column
# df

(array([   145,    252,    390, ..., 199890, 199893, 199957]),)
total outliners in it  4272



# IQR inter quartile range

Sure, let me explain how the concepts of Q1 (the first quartile), Q3 (the third quartile), and the Interquartile Range (IQR) work:

Quartiles (Q1, Q3):

1) Q1 (First Quartile): It is the median of the lower half of the dataset. It represents the value below which 25% of the data falls.
2) Q3 (Third Quartile): It is the median of the upper half of the dataset. It represents the value below which 75% of the data falls.

Interquartile Range (IQR):

1) The IQR is a measure of statistical dispersion, or in simple terms, it's the range in which the middle 50% of the data values lie.
2) Mathematically, IQR is calculated as the difference between Q3 and Q1: IQR = Q3 - Q1.
3) The IQR is used in detecting outliers. According to the IQR rule, values outside the range of Q1 - 1.5 * IQR to Q3 + 1.5 * IQR are considered potential outliers.



In [19]:
# IQR 
# Calculate the first quartile (Q1) and third quartile (Q3) for 'fare_amount'
Q1 = df['fare_amount'].quantile(0.25)
Q3 = np.percentile(df['fare_amount'], 75, interpolation='midpoint')

# Calculate the Interquartile Range (IQR)
IQR = Q3 - Q1

# Print the results
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 6.0
Q3: 12.5
IQR: 6.5


/tmp/ipykernel_5620/2817034194.py:4: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  Q3 = np.percentile(df['fare_amount'], 75, interpolation='midpoint')


In [20]:
upper = df['fare_amount'] >= (Q3+1.5*IQR)
 
print("Upper bound:",Q3+1.5*IQR)
print(np.where(upper))
 
# Below Lower bound
lower = df['fare_amount'] <= (Q1-1.5*IQR)
print("Lower bound:", Q1-1.5*IQR)
print(np.where(lower))
# These are the outliers combining Upper Bounded Array and Lowe Bounded Array

Upper bound: 22.25
(array([     6,     30,     34, ..., 199982, 199985, 199997]),)
Lower bound: -3.75
(array([ 63395,  89322,  92063,  98875, 104080, 111589, 139272, 148803,
       151681, 164056, 190925]),)
